/*

    node build.js --release

    
    git reset --soft HEAD^
*/
// mark
var is_release = false
var drop_console = false

// bundle/page layout lives in build.cfg.js (merged from remote's cfg-module refactor)
const build_config = require('./build.cfg')
, auto_rebuild = build_config.auto_rebuild
, refresh_rebuild = build_config.refresh_rebuild
, bgd = build_config.bgd
, ppd = build_config.ppd
, bgfls = build_config.bgfls
, pppjslibs = build_config.pppjslibs
, popup_common = build_config.popup_common
, popup_services = build_config.popup_services
, page_defs = build_config.page_defs

// MoneyNex SDK build-time config (default public gateway / mainnet chain_id=0)
var mnx_cfg = {
    fullnode_url: 'http://wallet.hacash.com/fullnode',
    fullnode_host: null,
    chain_id: 0, // ChainId::MAINNET
}



// check command line argv
let pavs = process.argv
for(let i in pavs) {
    let p = pavs[i]
    if(p == '--release'){
        is_release = true
        drop_console = true
    }else if(p.indexOf('--fullnode-url=') == 0){
        mnx_cfg.fullnode_url = p.split('=')[1]
    }else if(p.indexOf('--fullnode-host=') == 0){
        mnx_cfg.fullnode_host = p.split('=')[1]
    }else if(p.indexOf('--chain-id=') == 0){
        mnx_cfg.chain_id = parseInt(p.split('=')[1])
    }
}

// Inject RPC config at build time: override login.js defaults fullnode_url / mnx_chain_id
var js_rplsfn = (fcon) => {
    fcon += `\n;fullnode_url = ${JSON.stringify(mnx_cfg.fullnode_url)};\n`
    if(mnx_cfg.chain_id !== 0){
        fcon += `\n;mnx_chain_id = ${mnx_cfg.chain_id};\n`
    }
    return fcon
}

let popups = (list) => {
    let ary = []
    for(let i in list) {
        let p = list[i]
        ary.push(`${ppd}${p}/${p}`)
    }
    return ary
}

var vuepuplist = (vuecomptpls, ext) => {
    let pups = []
    for(let i in vuecomptpls) {
        pups.push(`${ppd}${vuecomptpls[i]}/vue${ext?('.'+ext):''}`)
    }
    return pups
} 

// requires
// const vue = require('vue')
// const babel = require("@babel/core")
const http = require('http')
const path = require('path')
const fs = require('fs')
// other
const vue_compiler_dom = require('@vue/compiler-dom')
const less = require('less')
const csso = require('csso')
const uglifyjs = require("uglify-js")
const uglifyjsconfig = { compress: {
    unsafe: true, hoist_funs: true, hoist_vars: true, 
    toplevel: true,  drop_console: drop_console,
}, mangle: { toplevel: true }}
const htmlMinify = require('html-minifier')
const htmlMinifyOptions = {
  continueOnParseError: true,
  includeAutoGeneratedTags: true,
  removeAttributeQuotes: true,
  removeComments: true,
  removeRedundantAttributes: true,
  removeScriptTypeAttributes: true,
  removeStyleLinkTypeAttributes: true,
  useShortDoctype: true,
  collapseWhitespace: true
}



////////////////////////

async function mergeFile(etx, fss, tarf, hdf, beforeist, rplsfn) {
    let fcons = [beforeist||'']
    for(let i in fss) {
        let f = fss[i]
        try{
            fcons.push( fs.readFileSync(f+"."+etx) + '')
        }catch(e){}
    }
    let fcon = fcons.join('\n') || ' '
    if(hdf) {
        fcon = await hdf(fcon)
    }
    if(rplsfn){
        fcon = rplsfn(fcon)
    }
    // dist
    fs.writeFileSync(tarf, fcon)
}

function jsminify(con) {
    // console.log(con)
    let res = uglifyjs.minify(con, uglifyjsconfig);
    if(res.error) {
        console.log(res.errpr)
        process.exit(0)
    }
    return res.code
}
function htmlminify(con) {
    return htmlMinify.minify(con, htmlMinifyOptions)
}

async function less2css(con) {
    let csscon = await less.render(con, {rewriteUrls: 'off'})
    let css = csscon.css.toString()
    if(is_release){
        css = csso.minify(css).css
    }
    return css
}

function release() {
    let bd = './release/'
    let dirs = [bd,
        bd+'background', 
        bd+'popup', 
        bd+'content', 
        bd+'image', 
        bd+'jslib', 
    ]
    for(let i in dirs) {
        try{ fs.mkdirSync(dirs[i]) }catch(e){}
    }
    cleanPageOutputs(bd+'popup')
    // Remove leftover SDK artifacts from previously generated releases
    // (old page-bundle name, and the separate wasm/zip that used to ship beside it),
    // and any test files an older build copied into the runtime jslib dir.
    for(const name of ['hacash_sdk2.js', 'hacash_sdk.wasm', 'hacash_wasm_sdk.zip']){
        try{ fs.unlinkSync(bd+'jslib/'+name) }catch(e){}
    }
    try{
        for(const f of fs.readdirSync(bd+'jslib')){
            if(f.endsWith('.test.js')){
                try{ fs.unlinkSync(bd+'jslib/'+f) }catch(e){}
            }
        }
    }catch(e){}
    // copy
    var cpfs = [
        'manifest.json',
        // 'background/hacash_sdk.wasm',
        'background/background.js',
        'content/content.min.js',
        'content/content.min.css',
        'content/hacash_api.min.js',
    ]
    for(let k in page_defs){
        cpfs = cpfs.concat([
            `popup/${k}.html`,
            `popup/${k}.css`,
            `popup/${k}.js`,
        ])
    }

    for(let i in cpfs){
        let f = cpfs[i];
        try{ 
            fs.copyFileSync('./'+f, bd+f)
        }catch(e){
            console.log(e)
        }
    }
    // Copy only runtime assets. Do not copy leftover wasm/zip artifacts
    // (or test files) into a release bundle where they can be mistaken for active code.
    const runtimeJslib = [
        'crypto-js.4.1.1.js', 'crypto-util.js', 'elliptic.min.js',
        'hacash_sdk.js', 'message-types.js', 'moneynx_sdk_facade.js',
        'msglayout.js', 'qrcode.min.js', 'vue.runtime.global.prod.js',
    ]
    copyDir('./image', bd+'image')
    for(const name of runtimeJslib){
        fs.copyFileSync('./jslib/'+name, bd+'jslib/'+name)
    }
    // Test build: append private-chain host_permissions to the release manifest (not injected for production builds)
    if(mnx_cfg.fullnode_host){
        let mf = JSON.parse(fs.readFileSync(bd+'manifest.json','utf8'))
        mf.host_permissions = mf.host_permissions || []
        if(mf.host_permissions.indexOf(mnx_cfg.fullnode_host) < 0){
            mf.host_permissions.push(mnx_cfg.fullnode_host)
        }
        fs.writeFileSync(bd+'manifest.json', JSON.stringify(mf, null, 2))
    }
}

function cleanPageOutputs(dir) {
    if(!fs.existsSync(dir)) return
    let keep = {}
    for(let k in page_defs) {
        keep[`${k}.html`] = true
        keep[`${k}.css`] = true
        keep[`${k}.js`] = true
    }
    for(let f of fs.readdirSync(dir)) {
        if(!/\.(html|css|js)$/.test(f)) continue
        if(!keep[f]) {
            try{ fs.unlinkSync(path.join(dir, f)) }catch(e){}
        }
    }
}

// Remove stale generated page outputs not in page_defs (remote's addition; keeps
// legacy bundles like popup/sign.* from shipping by accident)
function cleanPageOutputs(dir) {
    if(!fs.existsSync(dir)) return
    let keep = {}
    for(let k in page_defs) {
        keep[`${k}.html`] = true
        keep[`${k}.css`] = true
        keep[`${k}.js`] = true
    }
    for(let f of fs.readdirSync(dir)) {
        if(!/\.(html|css|js)$/.test(f)) continue
        if(!keep[f]) {
            try{ fs.unlinkSync(path.join(dir, f)) }catch(e){}
        }
    }
}

// Remove stale generated page outputs not in page_defs (remote's addition; keeps
// legacy bundles like popup/sign.* from shipping by accident)
function cleanPageOutputs(dir) {
    if(!fs.existsSync(dir)) return
    let keep = {}
    for(let k in page_defs) {
        keep[`${k}.html`] = true
        keep[`${k}.css`] = true
        keep[`${k}.js`] = true
    }
    for(let f of fs.readdirSync(dir)) {
        if(!/\.(html|css|js)$/.test(f)) continue
        if(!keep[f]) {
            try{ fs.unlinkSync(path.join(dir, f)) }catch(e){}
        }
    }
}

function getVueTplToJs(tpls, is_release) {
    var fnstrs = ['_Vue = Vue']
    for(let i in tpls) {
        // console.log('./popup/'+tpls[i]+'/vue.html')
        let t = tpls[i]
        , id = t.split('/').pop()
        , con = fs.readFileSync('./popup/'+t+'/vue.html')+''
        , cdd = vue_compiler_dom.compile(con, {
            // optimizeImports: true, prefixIdentifiers: true,
        })
        , vfn = `vue_tpl_${id} = function(){ ${cdd.code} }`
        if(is_release){
            // vfn = babel.transformSync(vfn,{ }).code   
        }
        fnstrs.push(vfn)
        // console.log(cdd.code)
    }
    return 'var ' + fnstrs.join("\n,") + ';'
}

// build
async function build(is_release) {


    // content    
    await mergeFile('js', [
        './jslib/message-types', 'content/define', 'content/hacash_api' 
    ], `content/hacash_api.min.js`, is_release?jsminify:null)
    await mergeFile('js', [
        './jslib/message-types', 'content/define', 'content/content'
    ], `content/content.min.js`, is_release?jsminify:null)
    await mergeFile('less', ['content/content'], `content/content.min.css`, less2css)
    // background
    await mergeFile('js', bgfls, `${bgd}background.js`, is_release?jsminify:null, null, js_rplsfn)


    // build page: moneynex and more 
    cleanPageOutputs(ppd)
    for(let k in page_defs){
        let v = page_defs[k]
        // buildPageSource 是 async：不 await 的话 release() 会在页面产物写完前就开始 copy，
        // 导致 release/ 里偶尔残留上一轮内容（改了源码但产物没变，需重跑一次才好）。
        await buildPageSource(k, v, is_release)
    }

    // build ok
    console.log(`build ${is_release?'release ':''}at ${new Date().toLocaleString()}`)   
}

// 

async function buildPageSource(pname, plist, is_release) {
    let plist_1 = ['login'].concat(plist[1], ['tail']) // add login and tail
    // console.log(plist_1)

    // vue tpl
    let beforejs = getVueTplToJs(popup_common[0].concat(plist[0]), is_release)
    , pupjss = pppjslibs
        .concat(popups(popup_common[1]))
        .concat(vuepuplist(popup_common[0]))
        .concat(vuepuplist(plist[0]))
        .concat(popup_services)
        .concat(popups(plist_1))
    
    // console.log(pupjss)
    await mergeFile('js', pupjss, `${ppd}${pname}.js`, is_release?jsminify:null, beforejs, js_rplsfn)
    await mergeFile('html', popups(popup_common[1]).concat(popups(plist_1)), `${ppd}${pname}.html`, is_release?htmlminify:null, null, res=>{
        return res.replace(
            `href=./popup.css`, `href=./${pname}.css`).replace(
            `src=./popup.js`, `src=./${pname}.js`)
    })
    let pupless = popups(popup_common[1]).concat(vuepuplist(popup_common[0])).concat(vuepuplist(plist[0])).concat(popups(plist_1))
    await mergeFile('less', pupless, `${ppd}${pname}.css`, less2css)

}

// run
async function run(is_release) {

    // do build
    await build(is_release)

    if(is_release){
        console.log(`do release...`) 
        release()
        console.log(`ok.`) 
    }else if(auto_rebuild){
        setTimeout(run, auto_rebuild*1000)
    }else if(refresh_rebuild){
        http.createServer(async function (request, response) {
            await build()
            response.end('rebuild ok');
        }).listen(7890);
    }
}


run(is_release).then()


/*

  const cdd = vue_compiler_dom.compile('<div>{{ msg }}</div>')
  console.log(cdd.code)
  
*/


////////////////////////




function copyDir(sd, td)  {
    const sourceFile = fs.readdirSync(sd, { withFileTypes: true })
    for (const file of sourceFile) {
      const srcFile = path.resolve(sd, file.name)
      const tagFile = path.resolve(td, file.name)
      if (file.isDirectory() && !fs.existsSync(tagFile)) {
        fs.mkdirSync(tagFile, err => console.log(err))
        copyDir(srcFile, tagFile)
      } else if (file.isDirectory() && fs.existsSync(tagFile)) {
        copyDir(srcFile, tagFile)
      }
      !file.isDirectory() && fs.copyFileSync(srcFile, tagFile, fs.constants.COPYFILE_FICLONE)
    }
  }
